# Generated by Django 5.2 on 2025-05-06 11:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("una_health_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlucoseTableLvels",
            fields=[
                ("device", models.CharField(max_length=40)),
                (
                    "serial_number",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("device_time_stamp", models.DateTimeField()),
                ("record_type", models.IntegerField(default=0)),
                ("glucose_history", models.IntegerField(blank=True, null=True)),
                ("glucose_scan", models.IntegerField(blank=True, null=True)),
                (
                    "non_numeric_rapid_acting_insulin",
                    models.TextField(blank=True, null=True),
                ),
                ("rapid_acting_insulin", models.FloatField(blank=True, null=True)),
                ("food_data", models.TextField(blank=True, null=True)),
                ("carbohydrates", models.IntegerField(blank=True, null=True)),
                (
                    "non_numeric_extended_release_insulin",
                    models.TextField(blank=True, null=True),
                ),
                ("extended_release_insulin", models.FloatField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("glucose_test_strip", models.IntegerField(blank=True, null=True)),
                ("ketone", models.FloatField(blank=True, null=True)),
                ("mealtime_insuline", models.FloatField(blank=True, null=True)),
                ("correction_insuline", models.FloatField(blank=True, null=True)),
                ("user_change_insulin", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.CharField(
                default=uuid.uuid4, max_length=100, primary_key=True, serialize=False
            ),
        ),
    ]
