# Generated by Django 5.2 on 2025-05-06 12:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("una_health_app", "0003_delete_glucosetablelvels"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlucoseTableLvels",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device", models.CharField(max_length=40)),
                ("serial_number", models.UUIDField(default=uuid.uuid4)),
                ("device_time_stamp", models.DateTimeField()),
                ("record_type", models.IntegerField(default=0)),
                ("glucose_history", models.IntegerField(blank=True, null=True)),
                ("glucose_scan", models.IntegerField(blank=True, null=True)),
                (
                    "non_numeric_rapid_acting_insulin",
                    models.TextField(blank=True, null=True),
                ),
                ("rapid_acting_insulin", models.FloatField(blank=True, null=True)),
                ("food_data", models.TextField(blank=True, null=True)),
                ("carbohydrates", models.IntegerField(blank=True, null=True)),
                (
                    "non_numeric_extended_release_insulin",
                    models.TextField(blank=True, null=True),
                ),
                ("extended_release_insulin", models.FloatField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("glucose_test_strip", models.IntegerField(blank=True, null=True)),
                ("ketone", models.FloatField(blank=True, null=True)),
                ("mealtime_insuline", models.FloatField(blank=True, null=True)),
                ("correction_insuline", models.FloatField(blank=True, null=True)),
                ("user_change_insulin", models.FloatField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="glucose_history",
                        to="una_health_app.user",
                    ),
                ),
            ],
        ),
    ]
