# Generated by Django 5.2 on 2025-05-06 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("una_health_app", "0004_glucosetablelvels"),
    ]

    operations = [
        migrations.AddField(
            model_name="glucosetablelvels",
            name="carbohydrates_servings",
            field=models.TextField(blank=True, null=True),
        ),
    ]
